USE CSE_3B_386

CREATE TABLE STU_INFO (
    RNO INT PRIMARY KEY,
    NAME VARCHAR(50),
    BRANCH VARCHAR(10)
);

INSERT INTO STU_INFO VALUES
(101, 'Raju', 'CE'),
(102, 'Amit', 'CE'),
(103, 'Sanjay', 'ME'),
(104, 'Neha', 'EC'),
(105, 'Meera', 'EE'),
(106, 'Mahesh', 'ME');

SELECT * FROM STU_INFO

CREATE TABLE RESULT (
    RNO INT,
    SPI DECIMAL(3,1),
    
);

INSERT INTO RESULT (RNO , SPI)VALUES
(101, 8.8),
(102, 9.2),
(103, 7.6),
(104, 8.2),
(105, 7.0);

SELECT * FROM RESULT

CREATE TABLE EMPLOYEE_MASTER (
    EMPLOYEENO VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(50),
    MANAGERNO VARCHAR(10),
    FOREIGN KEY (MANAGERNO) REFERENCES EMPLOYEE_MASTER(EMPLOYEENO)
);

INSERT INTO EMPLOYEE_MASTER  VALUES
('E01', 'Tarun', NULL),
('E02', 'Rohan', 'E02'),
('E03', 'Priya', 'E01'),
('E04', 'Milan', 'E03'),
('E05', 'Jay', 'E01'),
('E06', 'Anjana', 'E04');
SELECT * FROM EMPLOYEE_MASTER

DROP TABLE STU_INFO
DROP TABLE RESULT
DROP TABLE EMPLOYEE_MASTER

CREATE TABLE STU_INFO (
    RNO INT,
    NAME VARCHAR(50),
    BRANCH VARCHAR(10)
);

INSERT INTO STU_INFO VALUES
(101, 'Raju', 'CE'),
(102, 'Amit', 'CE'),
(103, 'Sanjay', 'ME'),
(104, 'Neha', 'EC'),
(105, 'Meera', 'EE'),
(106, 'Mahesh', 'ME');

SELECT * FROM STU_INFO

CREATE TABLE RESULT(
    RNO INT,
    SPI DECIMAL(3,1)
)

INSERT INTO RESULT VALUES
(101, 8.8),
(102, 9.2),
(103, 7.6),
(104, 8.2),
(105, 7.0),
(107,8.9);

SELECT * FROM RESULT

CREATE TABLE EMPLOYEE_MASTER(
    EMPLOYEENO VARCHAR(10),
    NAME VARCHAR(50),
    MANAGERNO VARCHAR(10),
)

INSERT INTO EMPLOYEE_MASTER  VALUES
('E01', 'Tarun', NULL),
('E02', 'Rohan', 'E02'),
('E03', 'Priya', 'E01'),
('E04', 'Milan', 'E03'),
('E05', 'Jay', 'E01'),
('E06', 'Anjana', 'E04');

SELECT * FROM EMPLOYEE_MASTER

---------Part – A:---------
--1. Combine information from student and result table using cross join or Cartesian product. 
SELECT * 
FROM STU_INFO ,RESULT

--2. Perform inner join on Student and Result tables. 
SELECT STU_INFO.RNO , STU_INFO.NAME , STU_INFO.BRANCH , RESULT.SPI 
FROM STU_INFO JOIN RESULT
ON STU_INFO.RNO = RESULT.RNO

--3. Perform the left outer join on Student and Result tables. 
SELECT STU_INFO.RNO , STU_INFO.NAME , STU_INFO.BRANCH
FROM STU_INFO LEFT OUTER JOIN RESULT
ON STU_INFO.RNO = RESULT.RNO

--4. Perform the right outer join on Student and Result tables. 
SELECT RESULT.RNO, RESULT.SPI
FROM STU_INFO RIGHT OUTER JOIN RESULT
ON STU_INFO.RNO = RESULT.RNO

--5. Perform the full outer join on Student and Result tables.  
SELECT STU_INFO.RNO , STU_INFO.NAME , STU_INFO.BRANCH , RESULT.SPI
FROM STU_INFO FULL OUTER JOIN RESULT
ON STU_INFO.RNO = RESULT.RNO

--6. Display Rno, Name, Branch and SPI of all students. 
SELECT STU_INFO.RNO , STU_INFO.NAME , STU_INFO.BRANCH , RESULT.SPI
FROM STU_INFO FULL OUTER JOIN RESULT
ON STU_INFO.RNO = RESULT.RNO

--7. Display Rno, Name, Branch and SPI of CE branch’s student only. 
SELECT STU_INFO.RNO , STU_INFO.NAME , STU_INFO.BRANCH , RESULT.SPI
FROM STU_INFO FULL OUTER JOIN RESULT
ON STU_INFO.RNO = RESULT.RNO
WHERE STU_INFO.BRANCH = 'CE'

--8. Display Rno, Name, Branch and SPI of other than EC branch’s student only. 
SELECT STU_INFO.RNO , STU_INFO.NAME , STU_INFO.BRANCH , RESULT.SPI
FROM STU_INFO FULL OUTER JOIN RESULT
ON STU_INFO.RNO = RESULT.RNO
WHERE STU_INFO.BRANCH != 'EC'

--9. Display average result of each branch.
SELECT STU_INFO.BRANCH , AVG(RESULT.SPI) AS AVG_SPI
FROM STU_INFO JOIN RESULT
ON STU_INFO.RNO = RESULT.RNO
GROUP BY STU_INFO.BRANCH

--10. Display average result of CE and ME branch. 
SELECT STU_INFO.BRANCH , AVG(RESULT.SPI) AS AVG_SPI
FROM STU_INFO JOIN RESULT
ON STU_INFO.RNO = RESULT.RNO
WHERE STU_INFO.BRANCH = 'CE' or STU_INFO.BRANCH = 'ME'
GROUP BY STU_INFO.BRANCH

--11. Display Maximum and Minimum SPI of each branch. 
SELECT STU_INFO.BRANCH , MIN(RESULT.SPI) AS MIN_SPI , MAX(RESULT.SPI) AS MAX_SPI
FROM STU_INFO JOIN RESULT
ON STU_INFO.RNO = RESULT.RNO
GROUP BY STU_INFO.BRANCH

--12. Display branch wise student’s count in descending order.
SELECT STU_INFO.BRANCH , COUNT(RESULT.RNO) AS TOTAL_STUDENT
FROM STU_INFO JOIN RESULT
ON STU_INFO.RNO = RESULT.RNO
GROUP BY STU_INFO.BRANCH
ORDER BY COUNT(RESULT.RNO) DESC

-------------Part – B:-------------- 
--1. Display average result of each branch and sort them in ascending order by SPI. 
SELECT STU_INFO.BRANCH , AVG(RESULT.SPI) AS AVG_SPI
FROM STU_INFO JOIN RESULT
ON STU_INFO.RNO = RESULT.RNO
GROUP BY STU_INFO.BRANCH
ORDER BY AVG(RESULT.SPI) 

--2. Display highest SPI from each branch and sort them in descending order. 
SELECT STU_INFO.BRANCH , MAX(RESULT.SPI) AS MAX_SPI
FROM STU_INFO JOIN RESULT
ON STU_INFO.RNO = RESULT.RNO
GROUP BY STU_INFO.BRANCH
ORDER BY MAX(RESULT.SPI) DESC

--------------Part – C:-------------- 
--1. Retrieve the names of employee along with their manager’s name from the Employee table. 
SELECT EMPLOYEE.NAME AS EMPLOYEE_NAME , MANAGER.NAME AS MANAGER_NAME
FROM EMPLOYEE_MASTER AS EMPLOYEE JOIN EMPLOYEE_MASTER AS MANAGER
ON EMPLOYEE.MANAGERNO = MANAGER.EMPLOYEENO
