USE CSE_3B_386

SELECT * FROM DEPT
SELECT * FROM PERSON

-----------Part – A:------------

--1. Combine information from Person and Department table using cross join or Cartesian product. 
SELECT * 
FROM PERSON , DEPT 

--2. Find all persons with their department name 
SELECT PERSON.PERSONNAME , DEPT.DEPARTMENTNAME
FROM PERSON LEFT OUTER JOIN DEPT
ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID 

--3. Find all persons with their department name & code.
SELECT PERSON.PERSONNAME , DEPT.DEPARTMENTNAME , DEPT.DEPARTMENTCODE
FROM PERSON LEFT OUTER JOIN DEPT
ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID 

--4. Find all persons with their department code and location. 
SELECT DEPT.DEPARTMENTNAME , DEPT.LOCATION 
FROM PERSON LEFT OUTER JOIN DEPT
ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID 

--5. Find the detail of the person who belongs to Mechanical department. 
SELECT * 
FROM PERSON LEFT OUTER JOIN DEPT
ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID 
WHERE DEPT.DEPARTMENTNAME = 'MECHENICAL'

--6. Final person’s name, department code and salary who lives in Ahmedabad city.  
SELECT PERSON.PERSONNAME , DEPT.DEPARTMENTCODE , PERSON.SALARY
FROM PERSON LEFT OUTER JOIN DEPT
ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID 
WHERE PERSON.CITY = 'AHMEDABAD'

--7. Find the person's name whose department is in C-Block. 
SELECT PERSON.PERSONNAME 
FROM PERSON LEFT OUTER JOIN DEPT
ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID 
WHERE DEPT.LOCATION = 'C-BLOCK'

--8. Retrieve person name, salary & department name who belongs to Jamnagar city. 
SELECT PERSON.PERSONNAME , DEPT.DEPARTMENTNAME , PERSON.SALARY
FROM PERSON LEFT OUTER JOIN DEPT
ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID 
WHERE PERSON.CITY = 'JAMNAGAR'

--9. Retrieve person’s detail who joined the Civil department after 1-Aug-2001. 
SELECT *
FROM PERSON LEFT OUTER JOIN DEPT
ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID 
WHERE PERSON.JOININGDATE > '01-08-2001' and DEPT.DEPARTMENTNAME = 'CIVIL'

--10. Display all the person's name with the department whose joining date difference with the current date 
--is more than 365 days. 
SELECT PERSON.PERSONNAME , DEPT.DEPARTMENTNAME
FROM PERSON LEFT OUTER JOIN DEPT
ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID 
WHERE DATEDIFF(DAY,PERSON.JOININGDATE,GETDATE()) > 365

--11. Find department wise person counts. 
SELECT COUNT(PERSON.PERSONNAME)
FROM PERSON LEFT OUTER JOIN DEPT
ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID 

--12. Give department wise maximum & minimum salary with department name. 
SELECT DEPT.DEPARTMENTNAME , MAX(PERSON.SALARY) , MIN(PERSON.SALARY)
FROM PERSON LEFT OUTER JOIN DEPT
ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID 
GROUP BY DEPT.DEPARTMENTNAME

--13. Find city wise total, average, maximum and minimum salary.
SELECT PERSON.CITY , SUM(PERSON.SALARY) , AVG(PERSON.SALARY) , MIN(PERSON.SALARY) , MAX(PERSON.SALARY)
FROM PERSON LEFT OUTER JOIN DEPT
ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID 
GROUP BY PERSON.CITY

--14. Find the average salary of a person who belongs to Ahmedabad city. 
SELECT AVG(PERSON.SALARY)
FROM PERSON LEFT OUTER JOIN DEPT
ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID 
WHERE PERSON.CITY = 'AHMEDABAD'


--15. Produce Output Like: <PersonName> lives in <City> and works in <DepartmentName> Department. (In 
--single column)
SELECT PERSON.PERSONNAME+' LIVES IN '+PERSON.CITY+' AND WORKS IN '+DEPT.DEPARTMENTNAME+' DEPARTMENT ' AS INFO
FROM PERSON LEFT OUTER JOIN DEPT
ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID 
